### ISSUE TITLE
How to accelerometer alert 

### ISSUE THREAD

**Issue by PekkaJalonen** [ruuvi-friends/ruuvi-hass.io#13]
Hello, can you give an example for RuuviTag accelerometer change alert. Best way of doing this would be to combine 3 axis into one sensor, but example just counting the values into one gives a lot of false positives when hass counts the values and all x,y and z are not always available.

**Comment by sergioisidoro** [comment]
Hi @PekkaJalonen, 

Sorry this project just provides data into Home Assistant project. If you would like to know how to setup "alerts" (I assume notifications) in home assistant you could start here: https://www.home-assistant.io/integrations/notify/

But I can give you an example of what I'm doing. Using the Telegram integration, I have a configuration that notifies me when Sauna is read:

```
sensors
  - platform: ruuvi
    sensors: 
      - mac: 'YOUR:RUUVI:MAC:ADDRESS'
        name: 'Sauna'

telegram_bot:
  - platform: polling
    api_key: SECRET-KEY-FROM-YOUR-BOT
    allowed_chat_ids:
      - ID-OF-YOUR-CHAT
      
automations:
  - alias: "Sauna is ready!"
    trigger:
      platform: numeric_state
      entity_id: sensor.sauna_temperature
      above: 60
      for:
          minutes: 5
    action:
      - service: telegram_bot.send_message
        data_template: 
          message: &SAUNA_STATUS |
            🔥 *SAUNA IS READY!* 🍺
            Current temperature is: {{states('sensor.sauna_temperature')}}
 ```
