### ISSUE TITLE
Collection of data stops after 1-2 hours

### ISSUE THREAD

**Issue by mkauttu** [ruuvi-friends/ruuvi-hass.io#38]
I have succesfully configured ruuvi-hass.io with couple of ruuvi tags. Data seems to come in for hour or two. After that data flow stops. Ruuvi tags continue to send out data, but HA -server does not recognize it. Restarting of HA (configuration --> Settings --> Server Controls --> Restart) will fix the issue. Of course rebooting of the entire server helps too. I'm running HASS.io official image on VMWare vSphere. Home Assistant version is 2021.12.10

**Comment by japekka** [comment]
Ihave also this issue. I will try to check if I could find some information in logs so that it could be useful to this case

**Comment by japekka** [comment]
After setting **adapter: "hci1"** the data seems to flow.
In my installation there are two different bluetooth adapters visible, but you could try to set that value.
Remember to change hci1 value to correspond your setup

**Comment by lraty** [comment]
Worked 10 days for me. Then needed reboot. Can I somehow add watchdog for this?

**Comment by mkauttu** [comment]
I created an automation to act as a watchdog. It runs every 5 minutes to check if latest update from a sensor is newer that 1800 seconds. If last update is more that 1800 seconds old host os reboots. Here is tha YAML. Jsut change the entity ID (sensor.outside_temperature) to match your's:

```
alias: Reboot if no data from ruuvi in 30 min
description: ''
trigger:
  - platform: time_pattern
    minutes: /5
condition:
  - condition: template
    value_template: >-
      {{
      (as_timestamp(now())-as_timestamp(states.sensor.outside_temperature.last_updated))
      | int > 1800}}
action:
  - service: hassio.host_reboot
    data: {}
mode: single
```
